name: zapxx
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+3

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1  
  url_launcher: ^6.3.1
  google_maps_flutter: ^2.12.1
  logger: ^2.5.0
  geolocator: ^13.0.4
  geocoding: ^3.0.0
  flutter_stripe: ^11.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_secure_storage: ^9.0.0
  fluttertoast: ^8.2.4
  http: ^1.2.0
  file_picker: ^9.0.0
  image_picker: ^1.1.2
  another_flushbar: ^1.12.30
  cached_network_image: ^3.3.1
  get_it: ^8.0.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get: ^4.6.6
  flutter_otp_text_field: ^1.2.0
  flutter_screenutil: ^5.9.3
  share_plus: ^10.0.2
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.0.7
  timetable_view: ^0.3.0
  flutter_slidable: ^4.0.0
  flutter_staggered_grid_view: ^0.7.0
  syncfusion_flutter_charts: ^28.2.6
  expansion_tile_card: ^3.0.0
  dotted_border: ^2.1.0
  gap: ^3.0.1
  syncfusion_flutter_datepicker: ^28.2.6
  intl: ^0.20.2
  flutter_time_picker_spinner: ^2.0.0
  flutter_image_slideshow: ^0.1.6
  widget_to_marker: ^1.0.6
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/map_style.json
  fonts:
    - family: nunito sans
      fonts:
        - asset: assets/fonts/nunito-sans/NunitoSans-Regular.ttf
        - asset: assets/fonts/nunito-sans/NunitoSans-Light.ttf
        - asset: assets/fonts/nunito-sans/NunitoSans-SemiBold.ttf
        - asset: assets/fonts/nunito-sans/NunitoSans-Bold.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.otf
        - asset: assets/fonts/poppins/Poppins-SemiBold.otf
        - asset: assets/fonts/poppins/Poppins-Medium.otf
        - asset: assets/fonts/poppins/Poppins-Light.otf
        - asset: assets/fonts/poppins/Poppins-Regular.otf  